### ISSUE TITLE
Vienminer and EBXL conflict

### ISSUE THREAD

**Issue by Scratchman** [ExtrabiomesXL/ExtrabiomesXL#443] opened 2015-11-26 07:33 UTC
i was looking at a friends error log for an unrelated error and saw this, thought it might eb interesting to you. I haven;t noticed any strange behaviour from vienminer because of it but veinminer is still new to the modpack.

[02:09:04] [Client thread/ERROR] [VeinMiner]: ERROR while looking at block with name %d. This is a bug with the respective mod.
[02:09:04] [Client thread/ERROR] [VeinMiner]: catching
java.lang.ArrayIndexOutOfBoundsException: 3
        at extrabiomes.items.ItemCustomMoreLeaves.func_77667_c(ItemCustomMoreLeaves.java:24) ~[ItemCustomMoreLeaves.class:?]
        at net.minecraft.item.Item.func_77657_g(Item.java:547) ~[adb.class:?]
        at net.minecraft.item.Item.func_77653_i(Item.java:636) ~[adb.class:?]
        at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427) ~[add.class:?]
        at portablejim.veinminer.VeinMiner.postInit(VeinMiner.java:206) [VeinMiner.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
        at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311) [FMLClientHandler.class:?]
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) [bao.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

**Comment by allaryin** [comment] 2015-12-15 16:44
This is caused by the same thing that was causing the FZ issue in #439. Testing patch right now.

**Comment by allaryin** [comment] 2015-12-15 17:29
Appears to work on my end, awaiting confirmation before closing the issue and releasing the build to Curse.

**Closed** 2016-01-19 20:58 UTC
